<?php

use App\Models\Cms\Module;
use Illuminate\Database\Seeder;

class ModulesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         *
         * IMPORTANT ! ****************!
         * Do not change the modules ids
         * Todo : Maybe later we can find module by reference and remove the ids
         *
         */
        // TODO : Make module names tranlsatable !
        $data = [
            [
                'name' => 'Rendez-vous',
                'reference' => 'appointments',
                'is_menu_module' => true,
                'is_active' => 1,
                'order' => 150,
                'icon' => '',
                'backend_route' => 'back.appointments.index',
                'backend_controller' => 'Appointment',
                'backend_action' => 'index',
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => 'back.appointments.index',
                'front_namespace' => 'Front',
                'front_controller' => 'AppointmentsController',
                'frontend_action' => 'index',
                'is_on_backend_sidebar' => 0,
            ],
            [
                'name' => 'Gestion des aspims',
                'reference' => 'aspims',
                'is_menu_module' => true,
                'is_active' => 1,
                'order' => 150,
                'icon' => '',
                'backend_route' => 'back.aspims.index',
                'backend_controller' => 'Aspim',
                'backend_action' => 'index',
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => 'back.aspims.index',
                'front_namespace' => 'Front',
                'front_controller' => 'AspimsController',
                'frontend_action' => 'index',
                'is_on_backend_sidebar' => 0,
            ],
            [
                'name' => 'Gestionnaire des aspims',
                'reference' => 'gestionnaire_aspims',
                'is_menu_module' => true,
                'is_active' => 1,
                'order' => 151,
                'icon' => '',
                'backend_route' => 'back.gestionnaire_aspim.index',
                'backend_controller' => 'GestionnaireAspim',
                'backend_action' => 'index',
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => 'back.gestionnaire_aspim.index',
                'front_namespace' => 'Front',
                'front_controller' => 'GestionnaireAspimController',
                'frontend_action' => 'index',
                'is_on_backend_sidebar' => 0,
            ],
            [
                'name' => 'Accueil',
                'reference' => 'home',
                'is_active' => 0,
                'is_menu_module' => true,
                'order' => 50,
                'icon' => '',
                'backend_route' => 'back.front_home.index',
                'backend_controller' => 'FrontHomeController',
                'backend_action' => 'index',
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => 'back.home.index',
                'front_namespace' => 'Front',
                'front_controller' => 'HomeController', // Multiple home pages
                'frontend_action' => 'index',
                'is_on_backend_sidebar' => 0,
            ],
            [
                'name' => 'Plan du site',
                'reference' => 'sitemaps',
                'main_model' => 'App\Models\Cms\Sitemap',
                'is_active' => 0,
                'is_menu_module' => true,
                'order' => 50,
                'icon' => '',
                'backend_route' => 'back.sitemaps.index',
                'backend_controller' => 'SitemapsController',
                'backend_action' => 'index',
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => 'back.sitemaps.index',
                'front_namespace' => 'Front',
                'front_controller' => 'SitemapsController',
                'frontend_action' => 'index',
                'is_on_backend_sidebar' => 0,
            ],
            [
                'name' => 'Contact Page',
                'reference' => 'contact-messages',
                'main_model' => 'App\Models\Cms\ContactMessage',
                'is_active' => 1,
                'is_menu_module' => true,
                'order' => 50,
                'icon' => 'fa fa-envelope-o',
                'backend_route' => 'back.contact_messages.index',
                'backend_controller' => 'ContactMessage',
                'backend_action' => 'index',
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => 'back.contact_messages.index',
                'front_namespace' => 'Front',
                'front_controller' => 'ContactMessagesController',
                'frontend_action' => 'index',
                'is_on_backend_sidebar' => 1,
            ],
            [
                'name' => 'Bannières',
                'reference' => 'banners',
                'main_model' => 'App\Models\Cms\Banner',
                'widget_orderable_columns' => json_encode(['created_at', 'updated_at']),
                'is_active' => 1,
                'is_menu_module' => false,
                'order' => 150,
                'icon' => '',
                'backend_route' => 'back.banners.index',
                'backend_controller' => 'Banner',
                'backend_action' => 'index',
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => 'back.banner.index',
                'front_namespace' => 'Front',
                'front_controller' => 'BannersController',
                'frontend_action' => 'index',
                'is_on_backend_sidebar' => 1,
            ],
            [
                'name' => 'Files',
                'reference' => 'files',
                'main_model' => 'App\Models\Cms\File',
                'is_active' => 1,
                'is_menu_module' => true,
                'order' => 50,
                'icon' => '',
                'backend_route' => 'back.files.index',
                'backend_controller' => 'File',
                'backend_action' => 'index',
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => 'back.file.index',
                'front_namespace' => 'Front',
                'front_controller' => 'FilesController',
                'frontend_action' => 'index',
                'is_on_backend_sidebar' => 0,
            ],
            [
                'name' => 'FAQ',
                'reference' => 'faqs',
                'main_model' => 'App\Models\Cms\FaqItem',
                'widget_orderable_columns' => json_encode(['created_at', 'updated_at', 'order']),
                'is_active' => 1,
                'is_menu_module' => true,
                'order' => 50,
                'icon' => '',
                'backend_route' => 'back.faq_items.index',
                'backend_controller' => 'Faq',
                'backend_action' => 'index',
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => 'back.faq_items.index',
                'front_namespace' => 'Front',
                'front_controller' => 'FaqsController',
                'frontend_action' => 'index',
                'is_on_backend_sidebar' => 0,
            ],
            [
                'name' => 'Page',
                'reference' => 'pages',
                'main_model' => 'App\Models\Cms\Page',
                'is_active' => 1,
                'is_menu_module' => true,
                'order' => 50,
                'icon' => '',
                'backend_route' => 'back.pages.editByMenuId',
                'backend_controller' => 'Page',
                'backend_action' => 'index',
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => 'back.pages.index',
                'front_namespace' => 'Front',
                'front_controller' => 'PagesController',
                'frontend_action' => 'index',
                'is_on_backend_sidebar' => 0,
            ],
            [
                'name' => 'Produit',
                'reference' => 'products',
                'is_active' => 1,
                'is_menu_module' => false,
                'order' => 50,
                'icon' => '',
                'backend_route' => 'back.products.index',
                'backend_controller' => 'Product',
                'backend_action' => 'index',
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => 'back.products.index',
                'front_namespace' => 'Front',
                'front_controller' => 'ProductsController',
                'frontend_action' => 'index',
                'is_on_backend_sidebar' => 0,
            ],
            [
                'name' => 'Devis',
                'reference' => 'quotations',
                'is_active' => 1,
                'is_menu_module' => false,
                'order' => 150,
                'icon' => '',
                'backend_route' => 'back.quotations.index',
                'backend_controller' => 'Quotation',
                'backend_action' => 'index',
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => 'back.quotations.index',
                'front_namespace' => 'Front',
                'front_controller' => 'QuotationsController',
                'frontend_action' => 'index',
                'is_on_backend_sidebar' => 0,
            ],
            [
                'name' => 'Notifications',
                'reference' => 'notifications',
                'is_active' => 1,
                'is_menu_module' => false,
                'order' => 50,
                'icon' => 'fa fa-bell',
                'backend_route' => 'back.notifications.index',
                'backend_controller' => 'Notification',
                'backend_action' => 'index',
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => 'back.notifications.index',
                'front_namespace' => 'Front',
                'front_controller' => null,
                'frontend_action' => 'index',
                'is_on_backend_sidebar' => 1,
            ],
            [
                'name' => 'Gestion Menus',
                'reference' => 'menus',
                'main_model' => 'App\Models\Cms\Menu',
                'widget_orderable_columns' => json_encode(['created_at', 'updated_at', 'order']),
                'is_active' => 1,
                'is_menu_module' => false,
                'order' => 10,
                'icon' => '',
                'backend_route' => 'back.menus.index',
                'backend_controller' => 'Menus',
                'backend_action' => 'index',
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => 'back.menus.index',
                'front_namespace' => 'Front',
                'front_controller' => 'MenusController',
                'frontend_action' => 'index',
                'is_on_backend_sidebar' => 1,
            ],
            [
                'name' => 'Paramètres',
                'reference' => 'parameters',
                'is_active' => 1,
                'is_menu_module' => false,
                'order' => 60,
                'icon' => 'fa fa-cogs',
                'backend_route' => 'back.parameters.index',
                'backend_controller' => 'Parameters',
                'backend_action' => 'index',
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => 'back.parameters.index',
                'front_namespace' => 'Front',
                'front_controller' => null,
                'frontend_action' => 'index',
                'is_on_backend_sidebar' => 1,
            ],
            [
                'name' => 'File Manager',
                'reference' => 'lfm',
                'is_active' => 1,
                'is_menu_module' => false,
                'order' => 50,
                'icon' => 'fa fa-image',
                'backend_route' => 'back.custom-lfm',
                'backend_controller' => null,
                'backend_action' => null,
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => null,
                'front_namespace' => 'Front',
                'front_controller' => null,
                'frontend_action' => null,
                'is_on_backend_sidebar' => 1,
            ],
            [
                'name' => 'Access Control List',
                'reference' => 'acl',
                'is_active' => 1,
                'is_menu_module' => false,
                'order' => 50,
                'icon' => 'fa fa-lock',
                'backend_route' => null,
                'backend_controller' => null,
                'backend_action' => null,
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => null,
                'front_namespace' => 'Front',
                'front_controller' => null,
                'frontend_action' => null,
                'is_on_backend_sidebar' => 1,
            ],
            [
                'name' => 'Gestion des utilisateurs',
                'reference' => 'users-management',
                'is_active' => 1,
                'is_menu_module' => false,
                'order' => 50,
                'icon' => 'fa fa-user-plus',
                'backend_route' => 'back.users.index',
                'backend_controller' => null,
                'backend_action' => null,
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => null,
                'front_namespace' => 'Front',
                'front_controller' => null,
                'frontend_action' => null,
                'is_on_backend_sidebar' => 1,
                'parent_reference' => 'acl',
            ],
            [
                'name' => 'Gestion des rôles',
                'reference' => 'roles-management',
                'is_active' => 1,
                'is_menu_module' => false,
                'order' => 50,
                'icon' => 'fa fa-users',
                'backend_route' => 'back.roles.index',
                'backend_controller' => null,
                'backend_action' => null,
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => null,
                'front_namespace' => 'Front',
                'front_controller' => null,
                'frontend_action' => null,
                'is_on_backend_sidebar' => 1,
                'parent_reference' => 'acl',
            ],
            [
                'name' => 'Newsletter',
                'reference' => 'newsletter-subscriptions',
                'is_active' => 1,
                'is_menu_module' => false,
                'order' => 151,
                'icon' => 'fa fa-envelope-o',
                'backend_route' => 'back.newsletter_subscriptions.index',
                'backend_controller' => null,
                'backend_action' => null,
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => null,
                'front_namespace' => 'Front',
                'front_controller' => 'NewslettersController',
                'frontend_action' => null,
                'is_on_backend_sidebar' => 1,
                'parent_reference' => null,
            ],
            [
                'name' => 'Locales',
                'reference' => 'locales',
                'is_active' => 1,
                'is_menu_module' => false,
                'order' => 51,
                'icon' => 'fa fa-language',
                'backend_route' => 'back.locales.index',
                'backend_controller' => null,
                'backend_action' => null,
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => null,
                'front_namespace' => 'Front',
                'front_controller' => null,
                'frontend_action' => null,
                'is_on_backend_sidebar' => 1,
                'parent_reference' => null,
            ],
            [
                'name' => 'Modules',
                'reference' => 'modules',
                'is_active' => 1,
                'is_menu_module' => false,
                'order' => 51,
                'icon' => 'fa fa-industry',
                'backend_route' => 'back.modules.index',
                'backend_controller' => null,
                'backend_action' => null,
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => null,
                'front_namespace' => 'Front',
                'front_controller' => null,
                'frontend_action' => null,
                'is_on_backend_sidebar' => 0,
                'parent_reference' => null,
            ],
            [
                'name' => 'Posts',
                'reference' => 'posts',
                'is_active' => 1,
                'is_menu_module' => false,
                'order' => 50,
                'icon' => 'fa fa-file-text-o',
                'backend_route' => 'back.post_categories.index',
                'backend_controller' => null,
                'backend_action' => null,
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => null,
                'front_namespace' => 'Front',
                'front_controller' => 'PostsController',
                'frontend_action' => null,
                'is_on_backend_sidebar' => 0,
                'parent_reference' => null,
            ],
            [
                'name' => 'Trainings',
                'reference' => 'trainings',
                'main_model' => 'App\Models\Cms\Training',
                'widget_orderable_columns' => json_encode(['created_at', 'updated_at', 'start_date', 'end_date']),
                'is_active' => 1,
                'is_menu_module' => true,
                'order' => 50,
                'icon' => 'fa fa-calendar',
                'backend_route' => 'back.trainings.index',
                'backend_controller' => null,
                'backend_action' => null,
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => null,
                'front_namespace' => 'Front',
                'front_controller' => 'TrainingsController',
                'frontend_action' => null,
                'is_on_backend_sidebar' => 0,
                'parent_reference' => null,
            ],
            [
                'name' => 'Événements',
                'reference' => 'events',
                'main_model' => 'App\Models\Cms\Event',
                'widget_orderable_columns' => json_encode(['created_at', 'updated_at', 'start_date', 'end_date']),
                'is_active' => 1,
                'is_menu_module' => true,
                'order' => 50,
                'icon' => 'fa fa-calendar',
                'backend_route' => 'back.events.index',
                'backend_controller' => null,
                'backend_action' => null,
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => null,
                'front_namespace' => 'Front',
                'front_controller' => 'EventsController',
                'frontend_action' => null,
                'is_on_backend_sidebar' => 0,
                'parent_reference' => null,
            ],
            [
                'name' => 'Useful Links',
                'reference' => 'useful-links',
                'main_model' => 'App\Models\Cms\UsefulLink',
                'is_active' => 1,
                'is_menu_module' => true,
                'order' => 50,
                'icon' => 'fa fa-link',
                'backend_route' => 'back.useful_links.index',
                'backend_controller' => null,
                'backend_action' => null,
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => null,
                'front_namespace' => 'Front',
                'front_controller' => 'UsefulLinksController',
                'frontend_action' => null,
                'is_on_backend_sidebar' => 0,
                'parent_reference' => null,
            ],
            [
                'name' => 'Traductions',
                'reference' => 'app-texts',
                'is_active' => 1,
                'is_menu_module' => false,
                'order' => 50,
                'icon' => 'fa fa-language',
                'backend_route' => 'back.app_texts.index',
                'backend_controller' => null,
                'backend_action' => null,
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => null,
                'front_namespace' => 'Front',
                'front_controller' => null,
                'frontend_action' => null,
                'is_on_backend_sidebar' => 1,
                'parent_reference' => null,
            ],
            [
                'name' => 'Gestion Localités',
                'reference' => 'location-management',
                'is_active' => 1,
                'is_menu_module' => false,
                'order' => 50,
                'icon' => 'fa fa-globe',
                'backend_route' => '#',
                'backend_controller' => null,
                'backend_action' => null,
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => null,
                'front_namespace' => 'Front',
                'front_controller' => null,
                'frontend_action' => null,
                'is_on_backend_sidebar' => 1,
                'parent_reference' => null,
            ],
            [
                'name' => 'Pays',
                'reference' => 'countries',
                'is_active' => 1,
                'is_menu_module' => false,
                'order' => 50,
                'icon' => 'fa fa-globe',
                'backend_route' => 'back.countries.index',
                'backend_controller' => null,
                'backend_action' => null,
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => null,
                'front_namespace' => 'Front',
                'front_controller' => null,
                'frontend_action' => null,
                'is_on_backend_sidebar' => 1,
                'parent_reference' => 'location-management',
            ],
            [
                'name' => 'Gouvernorats',
                'reference' => 'governorates',
                'is_active' => 1,
                'is_menu_module' => false,
                'order' => 50,
                'icon' => 'fa fa-globe',
                'backend_route' => 'back.governorates.index',
                'backend_controller' => null,
                'backend_action' => null,
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => null,
                'front_namespace' => 'Front',
                'front_controller' => null,
                'frontend_action' => null,
                'is_on_backend_sidebar' => 1,
                'parent_reference' => 'location-management',
            ],
            [
                'name' => 'Villes',
                'reference' => 'cities',
                'is_active' => 1,
                'is_menu_module' => false,
                'order' => 50,
                'icon' => 'fa fa-globe',
                'backend_route' => 'back.cities.index',
                'backend_controller' => null,
                'backend_action' => null,
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => null,
                'front_namespace' => 'Front',
                'front_controller' => null,
                'frontend_action' => null,
                'is_on_backend_sidebar' => 1,
                'parent_reference' => 'location-management',
            ],
            [
                'name' => 'Zones',
                'reference' => 'zones',
                'is_active' => 1,
                'is_menu_module' => false,
                'order' => 50,
                'icon' => 'fa fa-globe',
                'backend_route' => 'back.zones.index',
                'backend_controller' => null,
                'backend_action' => null,
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => null,
                'front_namespace' => 'Front',
                'front_controller' => null,
                'frontend_action' => null,
                'is_on_backend_sidebar' => 1,
                'parent_reference' => 'location-management',
            ],
            [
                'name' => 'Partenaires',
                'reference' => 'partners',
                'main_model' => 'App\Models\Cms\Partner',
                'widget_orderable_columns' => json_encode(['created_at', 'updated_at', 'order']),
                'is_active' => 1,
                'is_menu_module' => true,
                'order' => 50,
                'icon' => 'fa fa-link',
                'backend_route' => 'back.partners.index',
                'backend_controller' => null,
                'backend_action' => null,
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => null,
                'front_namespace' => 'Front',
                'front_controller' => 'PartnersController',
                'frontend_action' => null,
                'is_on_backend_sidebar' => 0,
                'parent_reference' => null,
            ],
            [
                'name' => 'Actualités',
                'reference' => 'news',
                'main_model' => 'App\Models\Cms\News',
                'widget_orderable_columns' => json_encode(['created_at', 'updated_at', 'order']),
                'is_active' => 1,
                'is_menu_module' => true,
                'order' => 50,
                'icon' => 'fa fa-calendar',
                'backend_route' => 'back.news.index',
                'backend_controller' => null,
                'backend_action' => null,
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => null,
                'front_namespace' => 'Front',
                'front_controller' => 'NewsController',
                'frontend_action' => null,
                'is_on_backend_sidebar' => 0,
                'parent_reference' => null,
            ],
            [
                'name' => 'Widgets',
                'reference' => 'widgets',
                'is_active' => 1,
                'is_menu_module' => false,
                'order' => 100,
                'icon' => 'fa fa-puzzle-piece',
                'backend_route' => 'back.widgets.index',
                'backend_controller' => 'WidgetsController',
                'backend_action' => null,
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => null,
                'front_namespace' => null,
                'front_controller' => null,
                'frontend_action' => null,
                'is_on_backend_sidebar' => 1,
                'parent_reference' => null,
            ],
            [
                'name' => 'Média',
                'reference' => 'media',
                'main_model' => 'App\Models\Cms\MediaAlbum',
                'widget_orderable_columns' => json_encode(['created_at', 'updated_at', 'start_date', 'end_date']),
                'is_active' => 1,
                'is_menu_module' => true,
                'order' => 50,
                'icon' => 'fa fa-image',
                'backend_route' => 'back.media_albums.index',
                'backend_controller' => null,
                'backend_action' => null,
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => null,
                'front_namespace' => 'Front',
                'front_controller' => 'MediaFilesController',
                'frontend_action' => null,
                'is_on_backend_sidebar' => 0,
                'parent_reference' => null,
            ],
            [
                'name' => 'Témoignages',
                'reference' => 'testimonials',
                'main_model' => 'App\Models\Cms\Testimonial',
                'widget_orderable_columns' => json_encode(['created_at', 'updated_at']),
                'is_active' => 1,
                'is_menu_module' => true,
                'order' => 50,
                'icon' => 'fa fa-image',
                'backend_route' => 'back.testimonials.index',
                'backend_controller' => null,
                'backend_action' => null,
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => null,
                'front_namespace' => 'Front',
                'front_controller' => 'TestimonialsController',
                'frontend_action' => null,
                'is_on_backend_sidebar' => 0,
                'parent_reference' => null,
            ],
            [
                'name' => 'Dev Tools',
                'reference' => 'dev-tools',
                'is_active' => 1,
                'is_menu_module' => false,
                'order' => 1000,
                'icon' => 'fa fa-bug',
                'backend_route' => null,
                'backend_controller' => null,
                'backend_action' => null,
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => null,
                'front_namespace' => null,
                'front_controller' => null,
                'frontend_action' => null,
                'is_on_backend_sidebar' => 1,
            ],
            [
                'name' => 'Logs Dashboard',
                'reference' => 'logs-dashboard',
                'is_active' => 1,
                'is_menu_module' => false,
                'order' => 1000,
                'icon' => 'fa fa-code',
                'backend_route' => 'log-viewer::dashboard',
                'backend_controller' => null,
                'backend_action' => null,
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => null,
                'front_namespace' => null,
                'front_controller' => null,
                'frontend_action' => null,
                'is_on_backend_sidebar' => 1,
                'parent_reference' => 'dev-tools',
            ],
            [
                'name' => 'Log files',
                'reference' => 'logs-list',
                'is_active' => 1,
                'is_menu_module' => false,
                'order' => 1000,
                'icon' => 'fa fa-code',
                'backend_route' => 'log-viewer::logs.list',
                'backend_controller' => null,
                'backend_action' => null,
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => null,
                'front_namespace' => null,
                'front_controller' => null,
                'frontend_action' => null,
                'is_on_backend_sidebar' => 1,
                'parent_reference' => 'dev-tools',
            ],
            [
                'name' => 'Cache cleaner',
                'reference' => 'cache-cleaner',
                'is_active' => 1,
                'is_menu_module' => false,
                'order' => 1000,
                'icon' => 'fa fa-code',
                'backend_route' => 'back.cache-cleaner.index',
                'backend_controller' => null,
                'backend_action' => null,
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => null,
                'front_namespace' => null,
                'front_controller' => null,
                'frontend_action' => null,
                'is_on_backend_sidebar' => 1,
                'parent_reference' => 'dev-tools',
            ],
            [
                'name' => 'Route list',
                'reference' => 'route-list',
                'is_active' => 1,
                'is_menu_module' => false,
                'order' => 1000,
                'icon' => 'fa fa-code',
                'backend_route' => 'back.routes.index',
                'backend_controller' => null,
                'backend_action' => null,
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => null,
                'front_namespace' => null,
                'front_controller' => null,
                'frontend_action' => null,
                'is_on_backend_sidebar' => 1,
                'parent_reference' => 'dev-tools',
            ],
            [
                'name' => 'Programmes de jumelage',
                'reference' => 'programs',
                'main_model' => 'App\Models\Cms\Program',
                'widget_orderable_columns' => json_encode(['created_at', 'updated_at', 'order']),
                'is_active' => 1,
                'is_menu_module' => true,
                'order' => 50,
                'icon' => 'fa fa-link',
                'backend_route' => 'back.programs.index',
                'backend_controller' => null,
                'backend_action' => null,
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => null,
                'front_namespace' => 'Front',
                'front_controller' => 'ProgramsController',
                'frontend_action' => null,
                'is_on_backend_sidebar' => 0,
                'parent_reference' => null,
            ],
            [
                'name' => 'Map layers',
                'reference' => 'map_layers',
                'main_model' => 'App\Models\Cms\MapLayer',
                'widget_orderable_columns' => json_encode(['created_at', 'updated_at', 'order']),
                'is_active' => 1,
                'is_menu_module' => true,
                'order' => 50,
                'icon' => 'fa fa-link',
                'backend_route' => 'back.map_layers.index',
                'backend_controller' => null,
                'backend_action' => null,
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => null,
                'front_namespace' => 'Front',
                'front_controller' => 'MapLayersController',
                'frontend_action' => null,
                'is_on_backend_sidebar' => 1,
                'parent_reference' => null,
            ],
            /* This is the default template !
            // Dont delete it: Just copy it !
            [
                'name' => 'Module Name',
                'reference' => 'module-reference',
                'is_active' => 1,
                'is_menu_module' => true,
                'order' => 50,
                'icon' => 'fa fa-exclamation-circle',
                'backend_route' => 'back.route_name.index',
                'backend_controller' => null,
                'backend_action' => null,
                'except_backend_actions' => null,
                'only_backend_actions' => null,
                'frontend_route' => null,
                'front_namespace' => 'Front',
                'front_controller' => null,
                'frontend_action' => null,
                'is_on_backend_sidebar' => 1,
                'parent_reference' => null,
            ],
            */
        ];

        Cache::forget('active_locales'); // Update active locales [bugfix: during the installation of demo]
        config(['translatable.locales' => get_translatable_locales()]);
        $locales = get_translatable_locales();

        foreach ($data as $d) {

            $parent_id = self::getParentIdForModule($d);

            if (Module::where('reference', $d['reference'])->get()->isEmpty()) {
                $module = [
                    'reference' => $d['reference'],
                    'main_model' => $d['main_model'] ?? null,
                    'widget_orderable_columns' => $d['widget_orderable_columns'] ?? null,
                    'is_active' => $d['is_active'],
                    'is_menu_module' => $d['is_menu_module'],
                    'order' => $d['order'],
                    'icon' => $d['icon'],
                    'backend_route' => $d['backend_route'],
                    'frontend_route' => $d['frontend_route'],
                    'front_namespace' => $d['front_namespace'],
                    'front_controller' => $d['front_controller'],
                    'is_on_backend_sidebar' => $d['is_on_backend_sidebar'],
                    'parent_id' => $parent_id,
                ];
                foreach ($locales as $locale) {
                    $module[$locale]['name'] = $d['name'];
                }
                Module::create($module);
            }
        }
    }

    public static function getParentIdForModule(array $d)
    {
        if (isset($d['parent_reference']) && $d['parent_reference']) {
            return Module::where('reference', $d['parent_reference'])->first()->id ?? null;
        }

        return null;
    }
}
